name: Auto Assign
on:
    issues:
        types: [opened]
    pull_request:
        types: [opened]

jobs:
    assign:
        uses: flex-is/reusable-workflows/.github/workflows/auto-assign.yaml@main
        with:
            config_file: .github/auto-assign-local.yaml
        secrets: inherit
