name: Auto Assign
on:
    issues:
        types: [opened, edited, labeled, unlabeled]
    pull_request:
        types: [opened, edited, labeled, unlabeled]

jobs:
    assign:
        uses: flex-is/reusable-workflows/.github/workflows/auto-assign.yaml@main
        secrets: inherit
